/* Copyright 2025 The xLLM Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/jd-opensource/xllm/blob/main/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#pragma once

#include <cstdint>
#include <string>

namespace xllm {

// LoRARequest is the immutable descriptor of one adapter as it enters the
// engine. It is generated by the HTTP handler (or by the static
// --lora-modules CLI) and lives inside LoRARegistry.
//
// Field naming mirrors vLLM's `vllm/lora/request.py:LoRARequest` so business
// gateways using vLLM contracts port over 1:1.
struct LoRARequest {
  // Human-readable adapter name. This is what the user puts in the OpenAI
  // `model` field (e.g. "biz-A-v3"). Used for hashing / equality.
  std::string lora_name;

  // Engine-assigned monotonically increasing integer id. > 0 always; 0 is
  // reserved to mean "no adapter" so batches with mixed base+adapter can
  // encode base rows as int_id == 0.
  uint64_t lora_int_id = 0;

  // Filesystem or object-storage path where the adapter's PEFT files live.
  // The engine expects `adapter_config.json` and `adapter_model.safetensors`
  // under this path; validation happens in LoRAAdapterLoader, not here.
  std::string lora_path;

  // The name of the base model this adapter was trained against. Compared
  // against the running engine's base model at load time so a business
  // team cannot accidentally serve a Qwen3 adapter on a Llama base.
  std::string base_model_name;
};

}  // namespace xllm
